"use client";

import Link from "next/link";
import {
  AlertTriangle,
  Bot,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  FileCheck2,
  FilePlus2,
  Filter,
  Github,
  MoreHorizontal,
  RotateCcw,
  Search,
  XCircle,
} from "lucide-react";
import { useMemo, useState } from "react";
import { SectionTabs } from "@/components/dashboard/section-tabs";
import {
  Badge,
  Button,
  Card,
  EmptyState,
  MetricCard,
  PageHeader,
  Skeleton,
} from "@/components/dashboard/ui";
import { useReviews } from "@/hooks/use-reviews";
import { filterReviewItems, reviewPageInterval } from "@/lib/reviews-page";
import { toReviewViewModel, type ReviewViewModel } from "@/lib/reviews";

const PAGE_SIZE = 5;
const reviewAccent = [
  ["bg-violet-500", "bg-violet-50 text-violet-500 dark:bg-violet-950/50"],
  ["bg-amber-500", "bg-orange-50 text-orange-500 dark:bg-orange-950/50"],
  ["bg-rose-500", "bg-rose-50 text-rose-500 dark:bg-rose-950/50"],
  ["bg-emerald-500", "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50"],
  ["bg-slate-300 dark:bg-slate-600", "bg-slate-100 text-slate-500 dark:bg-slate-800"],
] as const;

function tone(status: string): "green" | "rose" | "amber" | "blue" {
  if (status === "Approved") return "green";
  if (status === "Rejected") return "rose";
  if (status === "Needs changes") return "amber";
  return "blue";
}

function formatUpdated(value: string | null): string {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(date);
}

function RiskBadge({ risk }: { risk: string | null }) {
  const normalized = risk?.toLowerCase();
  const classes = normalized === "high" || normalized === "critical"
    ? "bg-rose-50 text-rose-600 dark:bg-rose-950/50 dark:text-rose-300"
    : normalized === "medium"
      ? "bg-amber-50 text-amber-600 dark:bg-amber-950/50 dark:text-amber-300"
      : normalized
        ? "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-300"
        : "bg-slate-100 text-slate-500 dark:bg-slate-800";
  return <span className={`inline-flex rounded-md px-3 py-2 text-xs font-medium leading-none ${classes}`}>{risk ?? "Unknown"}</span>;
}

function ReviewRow({ review, index }: { review: ReviewViewModel; index: number }) {
  const accent = reviewAccent[index % reviewAccent.length];
  const scoreTone = review.score === null
    ? { text: "text-foreground-muted", fill: "bg-slate-300" }
    : review.score < 70
      ? { text: "text-rose-600", fill: "bg-rose-500" }
      : review.score < 80
        ? { text: "text-amber-600", fill: "bg-amber-500" }
        : { text: "text-emerald-600", fill: "bg-emerald-500" };
  const TypeIcon = review.type?.toLowerCase() === "create" ? FilePlus2 : FileCheck2;
  return (
    <div className="grid min-h-[106px] gap-3 px-5 py-3.5 lg:grid-cols-[minmax(330px,2.35fr)_minmax(135px,1fr)_minmax(125px,.9fr)_minmax(155px,1.15fr)_minmax(92px,.72fr)_minmax(76px,.62fr)_minmax(105px,.8fr)_24px] lg:items-center">
      <div className="grid min-w-0 grid-cols-[9px_46px_minmax(0,1fr)] items-center gap-3">
        <span className={`h-2.5 w-2.5 rounded-full ${accent[0]}`} />
        <span className={`grid h-11 w-11 place-items-center rounded-lg ${accent[1]}`}><FileCheck2 aria-hidden="true" className="h-5 w-5" /></span>
        <div className="min-w-0">
          <div className="flex min-w-0 items-center gap-2">
            <Link href={`/reviews/${review.id}`} className="truncate text-sm font-semibold text-foreground hover:text-brand">{review.title}</Link>
            {review.reference && <Badge tone="violet">{review.reference}</Badge>}
          </div>
          <p className="mt-1 line-clamp-2 max-w-[325px] text-[11px] leading-[16px] text-foreground-muted">{review.description}</p>
          <p className="mt-1.5 flex items-center gap-1.5 text-[10px] text-foreground-muted"><Bot aria-hidden="true" className="h-3.5 w-3.5" />Generated by Documentation Agent</p>
        </div>
      </div>
      <div className="min-w-0 text-xs">
        <div className="flex items-center gap-2 font-medium text-foreground"><Github aria-hidden="true" className="h-4 w-4" />{review.repository ?? "Unknown repository"}</div>
        <div className="mt-1 truncate text-[11px] text-foreground-muted">{review.path ?? "No file path"}</div>
      </div>
      <div className="flex min-w-0 items-center gap-2 text-xs text-foreground-secondary">
        <span className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-blue-50 text-blue-600 dark:bg-blue-950/50"><TypeIcon aria-hidden="true" className="h-4 w-4" /></span>
        <span className="max-w-[90px] leading-[18px]">{review.type ?? "Unknown"}</span>
      </div>
      <div className="min-w-0">
        <div className={`text-base font-semibold ${scoreTone.text}`}>{review.score === null ? "—" : `${Math.round(review.score)}%`}</div>
        <div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${scoreTone.fill}`} style={{ width: `${review.score ?? 0}%` }} /></div>
        <div className="mt-1.5 text-[10px] text-foreground-muted">{review.evaluationCount === null ? "—" : `${review.evaluationCount} evaluations`}</div>
      </div>
      <RiskBadge risk={review.risk} />
      <span className="text-xs text-foreground-muted">{formatUpdated(review.updatedAt)}</span>
      <Badge tone={tone(review.status)}>{review.status}</Badge>
      <button type="button" aria-label={`More actions for ${review.title}`} className="grid h-8 w-8 place-items-center rounded-md text-foreground-muted hover:bg-surface-subtle hover:text-foreground"><MoreHorizontal aria-hidden="true" className="h-4 w-4" /></button>
    </div>
  );
}

function LoadingRows() {
  return <Card className="space-y-3 p-5">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-20 w-full" />)}</Card>;
}

export function ReviewsPage() {
  const [cursor, setCursor] = useState<string | undefined>();
  const [cursorHistory, setCursorHistory] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  const [repository, setRepository] = useState("");
  const [type, setType] = useState("");
  const [risk, setRisk] = useState("");
  const [score, setScore] = useState("");
  const { data, error, isLoading, isRefreshing, refresh } = useReviews({ limit: PAGE_SIZE, cursor });
  const reviews = useMemo(() => (data?.items ?? []).map(toReviewViewModel), [data?.items]);
  const filtered = useMemo(() => filterReviewItems(reviews, { query, repository, type, risk, score }), [reviews, query, repository, type, risk, score]);
  const repositories = useMemo(() => [...new Set(reviews.map((review) => review.repository).filter((value): value is string => Boolean(value)))], [reviews]);
  const types = useMemo(() => [...new Set(reviews.map((review) => review.type).filter((value): value is string => Boolean(value)))], [reviews]);
  const risks = useMemo(() => [...new Set(reviews.map((review) => review.risk).filter((value): value is string => Boolean(value)))], [reviews]);
  const counts = data?.counts;
  const startIndex = cursorHistory.length * PAGE_SIZE;
  const selectClass = "h-10 rounded-lg border border-border bg-surface px-3 text-sm text-foreground-secondary";

  return <>
    <PageHeader title="Reviews" subtitle="Review AI-generated documentation changes before they become part of your project knowledge." actions={<div className="flex gap-2"><Button>Configure reviews</Button><Button primary>+ New review</Button></div>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">
      <MetricCard label="Pending" value={counts?.pending ?? "—"} sub="Requires your review" icon={<FileCheck2 className="h-5 w-5" />} />
      <MetricCard label="Urgent" value={counts?.urgent ?? "—"} sub="High risk or low score" tone="rose" icon={<AlertTriangle className="h-5 w-5" />} />
      <MetricCard label="Approved" value={counts?.approved ?? "—"} sub="All recorded approvals" tone="green" icon={<CheckCircle2 className="h-5 w-5" />} />
      <MetricCard label="Needs changes" value={counts?.needs_changes ?? "—"} sub={counts ? "Explicit returned revisions" : "Unavailable from backend"} tone="amber" icon={<RotateCcw className="h-5 w-5" />} />
      <MetricCard label="Rejected" value={counts?.rejected ?? "—"} sub="All recorded rejections" icon={<XCircle className="h-5 w-5" />} />
    </div>
    <div className="mt-4"><SectionTabs section="reviews" reviewCounts={counts} /></div>
    <section aria-label="All reviews">
      <div className="my-4 flex flex-wrap items-center gap-3">
        <label className="relative min-w-[260px] flex-1 lg:max-w-[315px]"><span className="sr-only">Search reviews</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-foreground-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} type="search" placeholder="Search reviews..." className="h-10 w-full rounded-lg border border-border bg-surface pl-10 pr-3 text-sm text-foreground outline-none placeholder:text-foreground-muted focus:border-ring focus:ring-2 focus:ring-ring/20" /></label>
        <select aria-label="Repository" className={selectClass} value={repository} onChange={(event) => setRepository(event.target.value)}><option value="">Repository</option>{repositories.map((value) => <option key={value} value={value}>{value}</option>)}</select>
        <select aria-label="Review type" className={selectClass} value={type} onChange={(event) => setType(event.target.value)}><option value="">Review type</option>{types.map((value) => <option key={value} value={value}>{value}</option>)}</select>
        <select aria-label="Risk level" className={selectClass} value={risk} onChange={(event) => setRisk(event.target.value)}><option value="">Risk level</option>{risks.map((value) => <option key={value} value={value}>{value}</option>)}</select>
        <select aria-label="Score" className={selectClass} value={score} onChange={(event) => setScore(event.target.value)}><option value="">Score</option><option value="below80">Below 80%</option><option value="80to89">80–89%</option><option value="90plus">90%+</option></select>
        <button type="button" className="ml-auto inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-surface px-4 text-sm text-foreground-secondary hover:bg-surface-subtle"><Filter aria-hidden="true" className="h-4 w-4" />Filters</button>
      </div>
      {isLoading ? <LoadingRows /> : error && !data ? <Card className="p-8 text-center"><p className="text-sm text-danger">Unable to load reviews: {error}</p><Button className="mt-4" onClick={refresh}>Retry</Button></Card> : <>
        <Card className="overflow-hidden rounded-xl">
          <div className="hidden min-h-[38px] gap-3 border-b border-border bg-surface-subtle/45 px-5 text-[11px] font-medium text-foreground-muted lg:grid lg:grid-cols-[minmax(330px,2.35fr)_minmax(135px,1fr)_minmax(125px,.9fr)_minmax(155px,1.15fr)_minmax(92px,.72fr)_minmax(76px,.62fr)_minmax(105px,.8fr)_24px] lg:items-center"><span>Review</span><span>Repository</span><span>Type</span><span>AI Evaluation</span><span>Risk</span><span>Updated</span><span>Status</span><span /></div>
          <div className="divide-y divide-border">{filtered.map((review, index) => <ReviewRow key={review.id} review={review} index={index} />)}</div>
          {isRefreshing && <div className="border-t border-border px-5 py-2 text-xs text-foreground-muted">Refreshing reviews…</div>}
        </Card>
        {filtered.length === 0 && <div className="mt-4"><EmptyState icon={<FileCheck2 className="h-6 w-6" />} title={reviews.length ? "No matching reviews" : "No reviews yet"} description={reviews.length ? "Try changing your search or filters." : "New review requests will appear here when the backend creates them."} /></div>}
        <div className="mt-5 flex items-center justify-between pb-1 text-xs text-foreground-muted"><span>{reviewPageInterval(startIndex, filtered.length, data?.total ?? reviews.length)}</span><nav aria-label="Reviews pagination" className="flex items-center gap-2"><button type="button" aria-label="Previous page" disabled={cursorHistory.length === 0} onClick={() => { const previous = cursorHistory[cursorHistory.length - 1]; setCursorHistory((history) => history.slice(0, -1)); setCursor(previous || undefined); }} className="grid h-8 w-8 place-items-center rounded-lg border border-border bg-surface hover:bg-surface-subtle disabled:opacity-40"><ChevronLeft aria-hidden="true" className="h-4 w-4" /></button><span className="px-2">Page {cursorHistory.length + 1}</span><button type="button" aria-label="Next page" disabled={!data?.next_cursor} onClick={() => { if (!data?.next_cursor) return; setCursorHistory((history) => [...history, cursor ?? ""]); setCursor(data.next_cursor ?? undefined); }} className="grid h-8 w-8 place-items-center rounded-lg border border-border bg-surface hover:bg-surface-subtle disabled:opacity-40"><ChevronRight aria-hidden="true" className="h-4 w-4" /></button></nav></div>
      </>}
    </section>
  </>;
}

export default ReviewsPage;
