"use client";

import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { createWorkflow, listWorkflowTemplates, type WorkflowDefinitionInput, type WorkflowTemplate } from "@/api/workflows";
import { Button, Card, PageHeader } from "@/components/dashboard/ui";

export function WorkflowForm({ templateId }: { templateId?: string }) {
  const [templates, setTemplates] = useState<WorkflowTemplate[]>([]);
  const [form, setForm] = useState<WorkflowDefinitionInput>({ name: "", slug: "", workflow_key: "github_pr", description: "", trigger_config: { event: "pull_request.opened" }, review_config: { required: true } });
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => { listWorkflowTemplates(100).then((result) => { setTemplates(result.items); const selected = result.items.find((template) => template.id === templateId); if (selected) { const defaults = selected.defaults; setForm((current) => ({ ...current, ...defaults, workflow_key: selected.workflow_key, name: String(defaults.name ?? selected.name), slug: String(defaults.slug ?? selected.slug) })); } }).catch((err) => setError(err instanceof Error ? err.message : String(err))); }, [templateId]);
  const update = (key: keyof WorkflowDefinitionInput, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); try { const response = await createWorkflow(form); location.assign(`/workflows/${encodeURIComponent(response.workflow.id)}`); } catch (err) { setError(err instanceof Error ? err.message : String(err)); setSaving(false); } }

  return <><PageHeader title="Create workflow" subtitle="Create a persisted workflow definition that can be activated after validation." /><form onSubmit={submit} className="grid gap-4 lg:grid-cols-[1fr_320px]"><Card className="space-y-4 p-5"><div><label className="text-sm font-medium">Name<input required value={form.name} onChange={(event) => update("name", event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-border bg-input px-3 text-sm" placeholder="PR documentation" /></label></div><div><label className="text-sm font-medium">Slug<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug} onChange={(event) => update("slug", event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-border bg-input px-3 text-sm" placeholder="pr-documentation" /></label></div><div><label className="text-sm font-medium">Workflow type<select value={form.workflow_key} onChange={(event) => update("workflow_key", event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-border bg-input px-3 text-sm"><option value="github_pr">GitHub pull request</option><option value="github_release">GitHub release</option><option value="github_issue">GitHub issue</option><option value="documentation_sync">Documentation sync</option><option value="content_generation">Content generation</option></select></label></div><div><label className="text-sm font-medium">Description<textarea value={form.description ?? ""} onChange={(event) => update("description", event.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-border bg-input p-3 text-sm" placeholder="What this workflow automates" /></label></div><div className="flex justify-end gap-2"><Button type="button" onClick={() => history.back()}>Cancel</Button><Button primary type="submit" disabled={saving}>{saving ? "Creating…" : "Create workflow"}</Button></div>{error && <div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700" role="alert">{error}</div>}</Card><Card className="p-4"><h3 className="font-semibold">Templates</h3>{templates.length === 0 ? <p className="mt-3 text-xs text-foreground-muted">Loading templates…</p> : templates.map((template) => <button type="button" key={template.id} onClick={() => setForm((current) => ({ ...current, ...template.defaults, workflow_key: template.workflow_key, name: String(template.defaults.name ?? template.name), slug: String(template.defaults.slug ?? template.slug) }))} className="mt-3 block w-full rounded-xl border border-border p-3 text-left text-sm hover:bg-surface-subtle"><span className="font-medium">{template.name}</span><span className="mt-1 block text-xs text-foreground-muted">{template.description || template.workflow_key}</span></button>)}</Card></form></>;
}
