import Link from "next/link";
import { Activity, Bot, Database, FileCheck2, FileText, GitPullRequest, SearchCheck, ServerCog, Sparkles, Star, Workflow } from "lucide-react";
import { Badge, Card, IconTile, MetricCard, Progress, SectionTitle, TinyLink } from "@/components/dashboard/ui";
import { changeItems, evaluationItems, systemItems, workflowItems } from "./data";

export function SystemPulse() { const icons = [Bot, Database, SearchCheck, ServerCog]; return <Card><SectionTitle icon={<Activity className="h-4 w-4" />} title="System pulse" action={<Badge tone="green">● All systems operational</Badge>} /><div className="grid gap-2 p-4 sm:grid-cols-2 md:grid-cols-4">{systemItems.map(({ label, value }, index) => { const Icon = icons[index]; return <div key={label} className="rounded-xl border border-border p-3"><Icon className="h-4 w-4 text-brand" /><div className="mt-2 text-sm font-medium">{label}</div><div className="mt-1 text-xs text-success">● {value}</div></div>; })}</div></Card>; }
export function RecentChanges() { return <Card><SectionTitle icon={<Sparkles className="h-4 w-4" />} title="Recent documentation changes" action={<TinyLink href="/activity/document-changes">View all</TinyLink>} /><div className="divide-y divide-border px-4 pb-2">{changeItems.map(({ title, detail, time, status, tone }) => <Link href="/reviews" key={title} className="flex items-center gap-3 py-3"><IconTile size="sm" tone={tone}><FileText className="h-4 w-4" /></IconTile><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{title}</div><div className="truncate text-xs text-foreground-muted">{detail}</div></div><span className="hidden text-xs text-foreground-muted md:block">{time}</span><Badge tone={tone}>{status}</Badge></Link>)}</div></Card>; }
export function EvaluationResults() { return <Card><SectionTitle icon={<FileCheck2 className="h-4 w-4" />} title="Evaluation results" subtitle="Quality signals from recent runs" action={<TinyLink href="/evaluations">View all</TinyLink>} /><div className="grid gap-4 p-4 sm:grid-cols-[112px_1fr] sm:items-center"><div className="mx-auto grid h-28 w-28 place-items-center rounded-full border-[10px] border-success text-center"><div><strong className="text-2xl">92%</strong><div className="text-[10px] text-foreground-muted">Average score</div><Badge tone="green">↑ 4%</Badge></div></div><div className="grid min-w-0 gap-3">{evaluationItems.map(([name, value, tone]) => <div key={name}><div className="mb-1 flex items-center justify-between gap-2 text-xs"><span>{name}</span><span className="font-medium">{value}%</span></div><Progress value={value} tone={tone} /></div>)}</div></div></Card>; }
export function ActiveWorkflows() { return <Card><SectionTitle icon={<Workflow className="h-4 w-4" />} title="Active workflows" action={<TinyLink href="/workflows/active">View all</TinyLink>} /><div className="divide-y divide-border p-4">{workflowItems.map(({ name, repo, status, time, href }) => <Link href={href} key={name} className="flex gap-3 py-3 first:pt-0 last:pb-0"><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{name}</div><div className="mt-1 truncate text-xs text-foreground-muted">{repo}</div></div><div className="text-right text-xs"><div className={status === "Scheduled" ? "text-foreground-muted" : "text-success"}>● {status}</div><div className="mt-1 text-foreground-muted">{time}</div></div></Link>)}</div></Card>; }
function IntegrationCardIllustration() { return <svg aria-hidden="true" viewBox="0 0 132 188" className="pointer-events-none absolute inset-y-0 right-0 h-full w-[205px]" fill="none"><rect x="56" y="95" width="69" height="98" rx="8" fill="#9A8AF7" fillOpacity=".55" /><rect x="66" y="106" width="49" height="9" rx="4.5" fill="#8172F5" fillOpacity=".32" /><path d="M43 116a7 7 0 0 1 7-7h48a7 7 0 0 1 7 7v79H43v-79Z" fill="#D7D1FF" stroke="#9A8AF7" strokeWidth="1.25" /><path d="M29 127a7 7 0 0 1 7-7h49a7 7 0 0 1 7 7v68H29v-68Z" fill="white" stroke="#7764F2" strokeWidth="1.5" /><rect x="39" y="137" width="34" height="5" rx="2.5" fill="#6653EE" /><rect x="39" y="150" width="43" height="5" rx="2.5" fill="#8A79F7" /><rect x="39" y="163" width="29" height="5" rx="2.5" fill="#A69AF9" /></svg>; }
export function IntegrationPromo() { return <aside aria-labelledby="integration-promo-title" className="relative h-[292px] overflow-hidden rounded-xl border border-violet-100 bg-gradient-to-br from-violet-50/70 via-violet-50/90 to-blue-50 p-7 dark:border-violet-900/50 dark:from-violet-950/40 dark:via-violet-950/35 dark:to-blue-950/40"><div className="relative z-10 max-w-[270px]"><h3 id="integration-promo-title" className="text-lg font-semibold leading-6 text-foreground">Turn conversations<br />into better documentation</h3><p className="mt-3 text-sm leading-5 text-foreground-muted">Connect more data sources to help<br />Draftly stay up to date.</p></div><Link href="/integrations/add" className="absolute bottom-7 left-7 z-10 inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-surface px-5 text-[13px] font-medium text-brand transition-colors hover:bg-surface-subtle"><GitPullRequest className="h-[18px] w-[18px]" />Add integration</Link><IntegrationCardIllustration /></aside>; }
export function WorkspaceSummary() { return <section aria-label="Workspace summary" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Documentation" value="318" sub="Total documents" trend="12%" icon={<FileText />} /><MetricCard label="Active workflows" value="6" sub="3 running • 3 scheduled" trend="2" tone="violet" icon={<Activity />} /><MetricCard label="Review queue" value="12" sub="Pending human review" tone="green" icon={<FileCheck2 />} /><MetricCard label="Avg. evaluation score" value="92%" sub="Across all runs" trend="4%" tone="amber" icon={<Star />} /></section>; }
